[project]
name = "ttb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "flask>=3.1.2",
    "paddleocr>=3.3.2",
    "paddlepaddle>=3.2.2",
    "waitress>=3.0.2",
]
